version = 1

test_patterns = [
    "tests/unit/**"
]
exclude_patterns = [
    "tests/syntax/**",
    "tests/runtime/**"
    ]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
