version = 1

test_patterns = [
    "test_patterns = [",
    "    \"**/tests/unit/**\"",
    "]"
]

exclude_patterns = [
    "exclude_patterns = [",
    "    \"**/runtime_errors/**\",",
    "    \"**/syntax_errors/**\",",
    "]"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
