name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest]  # see https://github.com/tox-dev/tox/issues/1570
        tox:
          - env: py36
            python-version: '3.6'
          - env: py37
            python-version: '3.7'
          - env: py38
            python-version: '3.8'
          - env: py39
            python-version: '3.9'
        include:
          - tox:
              env: flake8,black
              python-version: '3.9'
            os: ubuntu-latest

    name: ${{ matrix.tox.env }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.tox.python-version }}
      - uses: actions/cache@v2
        with:
          path: |
            .tox
          key: ${{ matrix.os }}-${{ hashFiles('tox.ini') }}-${{ hashFiles('requirements-dev.txt') }}-${{ matrix.tox.python-version }}
      - name: setup tox
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: run ${{ matrix.tox.env }}
        run: |
          tox -q -e ${{ matrix.tox.env }} -p all
